version: "3"
services: 
  app:
    build: ./
    ports: 
    - "8080:80"
    environment: 
    - "content=dalong demo web page"
    - "DATA=(apple orange pear demo app rong)"
    - "DATA2=(rongfeng orange pear demo app rong)"